version: "3"
services:
  postgres:
    image: "postgres:12"
    environment:
      POSTGRES_DB: account_service
      POSTGRES_USER: account_service
      POSTGRES_PASSWORD: devPASSWORD
    logging:
      options:
        max-size: 100m
        max-file: "3"
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  account_django:
    build:
      context: ../..
      dockerfile: Dockerfile
    command: runserver 0.0.0.0:8000
    env_file: .env
    environment:
      DATABASE_PASSWORD: devPASSWORD
      DATABASE_HOST: postgres
      # defaults
      # DATABASE_USER: account_service
      # DATABASE_NAME: account_service
      # DATABASE_PORT: 5432
    logging:
      options:
        max-size: 100m
        max-file: "3"
    ports:
      # this needs to be set in the shell, compose env vars aren't read yet
      - "${DJANGO_PORT:-8000}:8000"
    volumes:
      - ../../src:/srv/service/main
      - ../../../fullctl/src/fullctl:/srv/service/venv/lib/python3.9/site-packages/fullctl

volumes:
  postgres_data:
