[tool.poetry]
name = "aaactl"
repository = "https://github.com/fullctl/aaactl"
version = "0.3.0-pr6"
description = "account control"
authors = ["20C <code@20c.com>"]
license = "Apache-2.0"

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Topic :: Software Development",
]


[tool.poetry.scripts]
aaactl = "aaactl.cli:main"


[tool.poetry.dependencies]
python = "^3.7"

# not in fullctl
python-dateutil = "*"
django-countries = "*"
django-cors-middleware = "*"
django-oauth-toolkit = "*"

pytest-filedata = "<1"
uWSGI = "^2.0.19"

fullctl = { git = "https://github.com/fullctl/fullctl.git", branch = "prep-release" }
stripe = "^2.55.2"

[tool.poetry.dev-dependencies]
# tests
pytest = ">=6.0.1"
pytest-django = ">=3.8.0"
pytest-cov = ">=2.7.1, <3"
pytest-mock = ">=3.2.0"
codecov = ">=2.0.15, <3"
coverage = ">=5, <6"

# linting
bandit = "^1.6.2"
black = "^20.8b1"
isort = "^5.7.0"
flake8 = "^3.8.4"
pyupgrade = "^2.19.3"

ctl = "^1.0.0"
tmpl = "^0.3.0"
pre-commit = "^2.13.0"
Jinja2 = "^2.11.3"
docker-compose = "^1.29.1"

[tool.isort]
profile = "black"
multi_line_output = 3
