[tool.poetry]
name = "aaactl"
repository = "https://github.com/fullctl/aaactl"
version = "0.1.0"
description = "account control"
authors = ["20C <code@20c.com>"]
license = "Apache-2.0"

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Topic :: Software Development",
]


[tool.poetry.scripts]
aaactl = "aaactl.cli:main"


[tool.poetry.dependencies]
python = "^3.7"

# not in fullctl
python-dateutil = "*"
django-countries = "*"
django-cors-middleware = "*"
django-oauth-toolkit = "*"

pytest-filedata = "<1"
uWSGI = "^2.0.19"

fullctl = { git = "https://github.com/fullctl/fullctl.git", branch = "prep_prod" }
stripe = "^2.55.2"

[tool.poetry.dev-dependencies]
docker-compose = "^1.29.1"
# tests
codecov = ">=2"
coverage = ">=5"
pytest = ">=6.0.1"
pytest-django = ">=3.8.0"
pytest-cov = "*"
pytest-mock = ">=3.2.0"
pytest-pythonpath = "*"

# linting
bandit = "^1.6.2"
black = {version = ">=20", allow-prereleases = true}
isort = "^5.7.0"
flake8 = "^3.8.4"
pre-commit = "^2.13.0"
pyupgrade = "^2.19.4"

# docs
markdown = "*"
markdown-include = ">=0.5,<1"
mkdocs = ">=1.0.0,<2.0.0"

# ctl
ctl = "^1.0.0"
jinja2 = "^2.11.2"
tmpl = "^0.3.0"


[tool.isort]
profile = "black"
multi_line_output = 3
