# Generated by Django 2.2.11 on 2020-03-12 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("account", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="apikeypermission",
            name="api_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keyperm_set",
                to="account.APIKey",
            ),
        )
    ]
