# Generated by Django 2.2.11 on 2020-03-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("account", "0002_auto_20200312_1013")]

    operations = [
        migrations.AlterModelManagers(name="apikeypermission", managers=[]),
        migrations.RenameField(
            model_name="apikeypermission", old_name="permissions", new_name="permission"
        ),
    ]
