# Generated by Django 2.2.11 on 2020-03-13 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("account", "0003_auto_20200312_1230")]

    operations = [migrations.AlterModelManagers(name="apikey", managers=[])]
