# Generated by Django 2.2.11 on 2020-03-23 14:25

from django.db import migrations, models

import account.models


class Migration(migrations.Migration):

    dependencies = [("account", "0008_organization_slug")]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.CharField(
                default=account.models.generate_org_slug, max_length=255, unique=True
            ),
        )
    ]
