# Generated by Django 2.2.11 on 2020-03-24 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
        ("account", "0011_auto_20200324_1131"),
    ]

    operations = [
        migrations.RemoveField(model_name="invitation", name="redirect"),
        migrations.AddField(
            model_name="invitation",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inv_set",
                to="applications.Service",
            ),
        ),
    ]
