# Generated by Django 2.2.12 on 2020-04-10 10:18

from django.db import migrations, models
import django.db.models.deletion
import django_grainy.fields


class Migration(migrations.Migration):

    dependencies = [("account", "0014_auto_20200327_1153")]

    operations = [
        migrations.AlterField(
            model_name="apikeypermission",
            name="api_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grainy_permissions",
                to="account.APIKey",
            ),
        ),
        migrations.AlterField(
            model_name="apikeypermission",
            name="namespace",
            field=models.CharField(
                help_text="Permission namespace (A '.' delimited list of keys",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="apikeypermission",
            name="permission",
            field=django_grainy.fields.PermissionField(default=1),
        ),
    ]
