# Generated by Django 2.2.13 on 2020-08-06 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_auto_20200410_1018"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inv_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="If set, designates this organzation as a user's personal organization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personal_org",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
