# Generated by Django 2.2.20 on 2021-04-23 11:30

import django_grainy.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_auto_20210422_0920"),
    ]

    operations = [
        migrations.AlterField(
            model_name="managedpermission",
            name="auto_grant_users",
            field=django_grainy.fields.PermissionField(
                help_text="Auto grants the permission at the following level to organization members and api keys"
            ),
        ),
    ]
