# Generated by Django 3.2.8 on 2022-03-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0021_usersettings_opt_promotions"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationuser",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="This organization is the user's designated default organization",
            ),
        ),
    ]
