# Generated by Django 3.2.14 on 2022-07-13 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0024_reftag_user_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailconfirmation",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_confirmation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organizationapikey",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_key_set",
                to="account.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationmanagedpermission",
            name="managed_permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_managed_permission_set",
                to="account.managedpermission",
            ),
        ),
        migrations.AlterField(
            model_name="organizationmanagedpermission",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_managed_permission_set",
                to="account.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationuser",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_user_set",
                to="account.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_user_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="organizationmanagedpermission",
            table="account_org_managed_permissions",
        ),
    ]
