# Generated by Django 3.2.14 on 2022-07-13 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_auto_20220708_1348"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0025_reftag_pass_1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invite_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invite_set",
                to="account.organization",
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invite_set",
                to="applications.service",
            ),
        ),
    ]
