# Generated by Django 3.2.14 on 2022-07-13 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_fieldnames'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0025_fix_permission_namespaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_set', to='account.organization'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_set', to='applications.service'),
        ),
        migrations.AlterField(
            model_name='organizationapikey',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_key_set', to='account.organization'),
        ),
        migrations.AlterField(
            model_name='organizationmanagedpermission',
            name='managed_permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_managed_permission_set', to='account.managedpermission'),
        ),
        migrations.AlterField(
            model_name='organizationmanagedpermission',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_managed_permission_set', to='account.organization'),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_user_set', to='account.organization'),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='invitation',
            table='account_inviteitation',
        ),
        migrations.AlterModelTable(
            name='organizationmanagedpermission',
            table='account_org_managed_permissions',
        ),
    ]
