# Generated by Django 3.2.14 on 2022-08-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0028_permission_roles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="managedpermissionroleautogrant",
            options={
                "verbose_name": "Permission assignment for role",
                "verbose_name_plural": "Permission assignments for roles",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationrole",
            options={
                "verbose_name": "User role within organization",
                "verbose_name_plural": "User roles within organization",
            },
        ),
        migrations.AddField(
            model_name="role",
            name="auto_set_on_creator",
            field=models.BooleanField(
                default=False,
                help_text="Automatically give the creators of an organization this role",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="auto_set_on_member",
            field=models.BooleanField(
                default=False,
                help_text="Automatically give new members of an organization this role",
            ),
        ),
    ]
