# Generated by Django 3.2.14 on 2022-08-11 13:12

from django.db import migrations


def create_roles(apps, schema_editor):

    Role = apps.get_model("account", "Role")

    Role.handleref.all().delete()

    Role.handleref.create(name="Admin", level=0, auto_set_on_creator=True)
    Role.handleref.create(name="Member", level=100, auto_set_on_member=True)


def create_auto_grants(apps, schema_editor):

    Role = apps.get_model("account", "Role")
    AutoGrant = apps.get_model("account", "ManagedPermissionRoleAutoGrant")
    ManagedPermission = apps.get_model("account", "ManagedPermission")

    AutoGrant.handleref.all().delete()

    admin = Role.handleref.get(name="Admin")
    member = Role.handleref.get(name="Member")

    for mperm in ManagedPermission.handleref.all():
        AutoGrant.handleref.create(managed_permission=mperm, role=admin, permissions=15)
        AutoGrant.handleref.create(managed_permission=mperm, role=member, permissions=1)


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0029_permission_roles_2"),
    ]

    operations = [
        migrations.RunPython(create_roles, migrations.RunPython.noop),
        migrations.RunPython(create_auto_grants, migrations.RunPython.noop),
    ]
