# Generated by Django 3.2.14 on 2022-08-16 13:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0031_user_permission_override"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userpermissionoverride",
            unique_together={("user", "org", "namespace")},
        ),
    ]
