# Generated by Django 3.2.14 on 2022-08-16 15:42

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_fullctl", "0020_auditlog_action_length"),
        ("account", "0032_alter_userpermissionoverride_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdatePermissions",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_fullctl.task",),
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="organizationrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_roles",
                to="account.role",
            ),
        ),
    ]
