# Generated by Django 3.2.15 on 2022-08-31 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0033_auto_20220816_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impersonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impersonating', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impersonation',
                'verbose_name_plural': 'Impersonations',
                'db_table': 'account_impersonation',
            },
        ),
    ]
