# Generated by Django 3.2.16 on 2023-04-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('support', 'Support'), ('feature-request', 'Feature Request')], default='general', max_length=255),
        ),
    ]
