# Generated by Django 3.2.16 on 2023-06-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0037_contactmessage_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("support", "Support"),
                    ("feature-request", "Feature Request"),
                    ("demo-request", "Demo Request"),
                ],
                default="general",
                max_length=255,
            ),
        ),
    ]
