# Generated by Django 3.2.23 on 2023-11-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    # replaces = [('account', '0039_auto_20231106_1624'), ('account', '0040_delete_admininvitation')]

    dependencies = [
        ("account", "0038_alter_contactmessage_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[("member", "Member"), ("admin", "Admin")],
                default="member",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("support", "Support"),
                    ("feature-request", "Feature Request"),
                    ("demo-request", "Demo Request"),
                    ("netdevops-primer", "NetDevOps Primer"),
                ],
                default="general",
                max_length=255,
            ),
        ),
    ]
