# Generated by Django 3.2.23 on 2023-11-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0039_auto_20231106_1624"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
