# Generated by Django 4.2.10 on 2024-03-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0041_authfederation_servicefederationsupport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="federatedserviceurl",
            name="config",
            field=models.JSONField(
                default=dict,
                help_text="Service specific configuration for this URL.",
                verbose_name="Service Configuration",
            ),
        ),
    ]
