# Generated by Django 4.2.10 on 2024-03-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0042_federatedserviceurl_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicefederationsupport",
            name="logo_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
