# Generated by Django 2.2.16 on 2021-01-12 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodifier",
            name="type",
            field=models.CharField(
                choices=[
                    ("reduction", "Price Reduction"),
                    ("quantity", "Free Quantity"),
                    ("free", "Free"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionmodifier",
            name="sub",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modifier_set",
                to="billing.Subscription",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionmodifier",
            name="type",
            field=models.CharField(
                choices=[
                    ("reduction", "Price Reduction"),
                    ("quantity", "Free Quantity"),
                    ("free", "Free"),
                ],
                max_length=255,
            ),
        ),
    ]
