# Generated by Django 2.2.16 on 2021-01-12 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_auto_20210112_0940"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SubscriptionModifier",
            new_name="SubscriptionProductModifier",
        ),
        migrations.RemoveField(
            model_name="subscriptionproductmodifier",
            name="sub",
        ),
        migrations.AddField(
            model_name="subscriptionproductmodifier",
            name="subprod",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modifier_set",
                to="billing.SubscriptionProduct",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productgroup",
            name="subscription_cycle_anchor",
            field=models.DateField(
                blank=True,
                help_text="If specified, sets a day of the month to be used as the anchor point for subscription cycles",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="recurringproduct",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price in the context of recurring charges. For fixed recurring pricing this would be the price charged each cycle. For metered pricing this would be the usage price per metered unit.",
                max_digits=6,
            ),
        ),
    ]
