# Generated by Django 2.2.17 on 2021-01-27 16:31

from django.db import migrations, models
import django.db.models.deletion

def null_components(apps, schema_editor):
    Product = apps.get_model("billing", "Product")
    
    for prod in Product.handleref.all():
    	prod.component = None
    	prod.save()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20210112_1041'),
    ]

    operations = [
	migrations.AlterField(
            model_name='product',
            name='component',
            field=models.CharField(max_length=255, blank=True, null=True, help_text='Product belongs to component'),
	),
    	migrations.RunPython(null_components),
        migrations.AlterField(
            model_name='product',
            name='component',
            field=models.ForeignKey(blank=True, help_text='Product belongs to component', null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.Service'),
        ),
    ]
