# Generated by Django 3.2.4 on 2021-08-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0006_auto_20210215_1905"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerdata",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="paymentcharge",
            name="data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Any extra data"
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="product",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Arbitrary extra data you want to define for this product",
            ),
        ),
        migrations.AlterField(
            model_name="recurringproduct",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Arbitrary extra data you want to define for this recurring product",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Any extra data for the subscription",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionproduct",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Any extra data for the subscription item",
            ),
        ),
    ]
