# Generated by Django 3.2.14 on 2022-07-13 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_auto_20210805_0835"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderhistoryitem",
            old_name="cycleprod",
            new_name="cycleproduct",
        ),
        migrations.RenameField(
            model_name="productmodifier",
            old_name="prod",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="recurringproduct",
            old_name="prod",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="subscriptionproduct",
            old_name="prod",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="subscriptionproductmodifier",
            old_name="subprod",
            new_name="subproduct",
        ),
        migrations.RenameField(
            model_name="subscriptioncycleproduct",
            old_name="subprod",
            new_name="subproduct",
        ),
        migrations.AlterField(
            model_name="product",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Allows you to group products together for billing purposes",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_set",
                to="billing.productgroup",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptioncycleproduct",
            name="cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cycleproduct_set",
                to="billing.subscriptioncycle",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionproduct",
            name="sub",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subproduct_set",
                to="billing.subscription",
            ),
        ),
    ]
