# Generated by Django 3.2.13 on 2022-07-13 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_auto_20210805_0835"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customerdata",
            old_name="billcon",
            new_name="billing_contact",
        ),
        migrations.RenameField(
            model_name="orderhistory",
            old_name="billcon",
            new_name="billing_contact",
        ),
        migrations.RenameField(
            model_name="orderhistoryitem",
            old_name="order",
            new_name="order_history",
        ),
        migrations.RenameField(
            model_name="paymentcharge",
            old_name="pay",
            new_name="payment_method",
        ),
        migrations.RenameField(
            model_name="paymentmethod",
            old_name="billcon",
            new_name="billing_contact",
        ),
        migrations.RenameField(
            model_name="productmodifier",
            old_name="prod",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="subscriptioncycle",
            old_name="sub",
            new_name="subscription",
        ),
        migrations.RenameField(
            model_name="subscriptioncyclecharge",
            old_name="cycle",
            new_name="subscription_cycle",
        ),
        migrations.RenameField(
            model_name="subscriptioncycleproduct",
            old_name="cycle",
            new_name="subscription_cycle",
        ),
        migrations.RenameField(
            model_name="subscriptioncycleproduct",
            old_name="subprod",
            new_name="subscription_product",
        ),
        migrations.RenameField(
            model_name="subscriptionproduct",
            old_name="prod",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="subscriptionproduct",
            old_name="sub",
            new_name="subscription",
        ),
        migrations.RenameField(
            model_name="subscriptionproductmodifier",
            old_name="subprod",
            new_name="subscription_product",
        ),
        migrations.RenameField(
            model_name="orderhistory",
            old_name="chg",
            new_name="payment_charge",
        ),
        migrations.RenameField(
            model_name="recurringproduct",
            old_name="prod",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="pay",
            new_name="payment_method",
        ),
        migrations.RenameField(
            model_name="subscriptioncyclecharge",
            old_name="chg",
            new_name="payment_charge",
        ),
        migrations.AlterField(
            model_name="orderhistoryitem",
            name="cycleprod",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_history_item",
                to="billing.subscriptioncycleproduct",
            ),
        ),
        migrations.AlterField(
            model_name="paymentcharge",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price attributed to subscription cycle for this product",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price charge on initial setup / purchase. For recurring product pricing this could specify a setup fee. For non-recurring product pricing, this is the product price.",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="recurringproduct",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Arbitrary extra data you want to define for this recurring product",
            ),
        ),
        migrations.AlterField(
            model_name="recurringproduct",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price in the context of recurring product charges. For fixed recurring product pricing this would be the price charged each subscription cycle. For metered pricing this would be the usage price per metered unit.",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="cycle_start",
            field=models.DateTimeField(
                blank=True, help_text="Start of billing subscription cycle", null=True
            ),
        ),
        migrations.AlterField(
            model_name="subscriptioncycleproduct",
            name="usage",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Usage attributed to subscription cycle for this product",
            ),
        ),
    ]
