# Generated by Django 3.2.14 on 2022-07-13 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_fix_permission_namespaces'),
        ('billing', '0008_reftag_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcontact',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_contact_set', to='account.organization'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='payment_charge',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history', to='billing.paymentcharge'),
        ),
        migrations.AlterField(
            model_name='recurringproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_product', to='billing.product'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.ForeignKey(help_text='User payment option that will be charged by this subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_set', to='billing.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='subscriptioncyclecharge',
            name='payment_charge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_cycle_charge', to='billing.paymentcharge'),
        ),
    ]
