# Generated by Django 3.2.14 on 2022-07-13 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_reftag_refactor_3'),
        ('billing', '0009_reftag_refactor_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistoryitem',
            old_name='cycleprod',
            new_name='subscription_cycle_product',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='cycle_frequency',
            new_name='subscription_cycle_frequency',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='cycle_interval',
            new_name='subscription_cycle_interval',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='cycle_start',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_cycle_start',
            field=models.DateTimeField(blank=True, help_text='Start of billing subscription subscription_cycle', null=True),
        ),
        migrations.AlterField(
            model_name='paymentcharge',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_charge_set', to='billing.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='paymentcharge',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price attributed to subscription subscription_cycle for this product', max_digits=6),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='billing_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_set', to='billing.billingcontact'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Allows you to group products together for billing purposes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_set', to='billing.productgroup'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price charge on initial setup / purchase. For recurring_product product pricing this could specify a setup fee. For non-recurring_product product pricing, this is the product price.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='subscription_cycle_anchor',
            field=models.DateField(blank=True, help_text='If specified, sets a day of the month to be used as the anchor point for subscription subscription_cycles', null=True),
        ),
        migrations.AlterField(
            model_name='recurringproduct',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Arbitrary extra data you want to define for this recurring_product product'),
        ),
        migrations.AlterField(
            model_name='recurringproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in the context of recurring_product product charges. For fixed recurring_product product pricing this would be the price charged each subscription subscription_cycle. For metered pricing this would be the usage price per metered unit.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_set', to='billing.productgroup'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_set', to='account.organization'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.ForeignKey(help_text='User payment option that will be charged by this subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_set', to='billing.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='subscriptioncycle',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_cycle_set', to='billing.subscription'),
        ),
        migrations.AlterField(
            model_name='subscriptioncyclecharge',
            name='subscription_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_cycle_charge_set', to='billing.subscriptioncycle'),
        ),
        migrations.AlterField(
            model_name='subscriptioncycleproduct',
            name='subscription_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_cycle_product_set', to='billing.subscriptioncycle'),
        ),
        migrations.AlterField(
            model_name='subscriptioncycleproduct',
            name='subscription_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_cycle_product_set', to='billing.subscriptionproduct'),
        ),
        migrations.AlterField(
            model_name='subscriptioncycleproduct',
            name='usage',
            field=models.PositiveIntegerField(default=0, help_text='Usage attributed to subscription subscription_cycle for this product'),
        ),
        migrations.AlterField(
            model_name='subscriptionproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_set', to='billing.product'),
        ),
        migrations.AlterField(
            model_name='subscriptionproduct',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptionproduct_set', to='billing.subscription'),
        ),
    ]
