# Generated by Django 3.2.14 on 2022-07-13 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0026_reftag_pass_2"),
        ("billing", "0009_reftag_pass_2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderhistoryitem",
            old_name="cycleproduct",
            new_name="subscription_cycle_product",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="cycle_frequency",
            new_name="subscription_cycle_frequency",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="cycle_interval",
            new_name="subscription_cycle_interval",
        ),
        migrations.RenameField(
            model_name="subscriptionproductmodifier",
            old_name="subproduct",
            new_name="subscription_product",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="cycle_start",
            new_name="subscription_cycle_start",
        ),
        migrations.RenameField(
            model_name="subscriptioncycle",
            old_name="sub",
            new_name="subscription",
        ),
        migrations.RenameField(
            model_name="subscriptioncyclecharge",
            old_name="cycle",
            new_name="subscription_cycle",
        ),
        migrations.RenameField(
            model_name="subscriptioncycleproduct",
            old_name="cycle",
            new_name="subscription_cycle",
        ),
        migrations.RenameField(
            model_name="subscriptioncycleproduct",
            old_name="subproduct",
            new_name="subscription_product",
        ),
        migrations.RenameField(
            model_name="subscriptionproduct",
            old_name="sub",
            new_name="subscription",
        ),
        migrations.AlterField(
            model_name="paymentcharge",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price attributed to subscription_cycle for this product",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="productgroup",
            name="subscription_cycle_anchor",
            field=models.DateField(
                blank=True,
                help_text="If specified, sets a day of the month to be used as the anchor point for subscription subscription_cycles",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="recurringproduct",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price in the context of recurring_product charges. For fixed recurring_product pricing this would be the price charged each subscription_cycle. For metered pricing this would be the usage price per metered unit.",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_set",
                to="billing.productgroup",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_set",
                to="account.organization",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="pay",
            field=models.ForeignKey(
                help_text="User payment option that will be charged by this subscription",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscription_set",
                to="billing.paymentmethod",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptioncyclecharge",
            name="chg",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_cycle_charge",
                to="billing.paymentcharge",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptioncycleproduct",
            name="usage",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Usage attributed to subscription_cycle for this product",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_set",
                to="billing.product",
            ),
        ),
    ]
