# Generated by Django 3.2.14 on 2022-07-13 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0010_reftag_pass_3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderhistoryitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_history_item_set",
                to="billing.orderhistory",
            ),
        ),
        migrations.AlterField(
            model_name="orderhistoryitem",
            name="subscription_cycle_product",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_history_item",
                to="billing.subscriptioncycleproduct",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscription_cycle_start",
            field=models.DateTimeField(
                blank=True, help_text="Start of billing subscription_cycle", null=True
            ),
        ),
        migrations.AlterField(
            model_name="subscriptioncycle",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_cycle_set",
                to="billing.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptioncyclecharge",
            name="subscription_cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_cycle_charge_set",
                to="billing.subscriptioncycle",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptioncycleproduct",
            name="subscription_cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_cycle_product_set",
                to="billing.subscriptioncycle",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptioncycleproduct",
            name="subscription_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_cycle_product_set",
                to="billing.subscriptionproduct",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionproduct",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_product_set",
                to="billing.subscription",
            ),
        ),
    ]
