# Generated by Django 3.2.14 on 2022-07-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_reftag_pass_2'),
        ('billing', '0011_reftag_pass_4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdata',
            old_name='billcon',
            new_name='billing_contact',
        ),
        migrations.RenameField(
            model_name='orderhistory',
            old_name='billcon',
            new_name='billing_contact',
        ),
        migrations.RenameField(
            model_name='orderhistory',
            old_name='chg',
            new_name='payment_charge',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='billcon',
            new_name='billing_contact',
        ),
        migrations.RenameField(
            model_name='subscriptioncyclecharge',
            old_name='chg',
            new_name='payment_charge',
        ),
        migrations.AlterField(
            model_name='billingcontact',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_contact_set', to='account.organization'),
        ),
        migrations.AlterField(
            model_name='paymentcharge',
            name='pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_charge_set', to='billing.paymentmethod'),
        ),
    ]
