# Generated by Django 3.2.14 on 2022-07-13 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0012_reftag_pass_5"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentcharge",
            old_name="pay",
            new_name="payment_method",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="pay",
            new_name="payment_method",
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="billing_contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_method_set",
                to="billing.billingcontact",
            ),
        ),
    ]
