# Generated by Django 3.2.16 on 2023-01-27 11:54

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_handleref.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_impersonation'),
        ('billing', '0013_reftag_pass_6'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPermissionGrant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', django_handleref.models.CreatedDateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', django_handleref.models.UpdatedDateTimeField(auto_now=True, verbose_name='Updated')),
                ('version', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('pending', 'Pending'), ('deactivated', 'Deactivated'), ('failed', 'Failed'), ('expired', 'Expired')], default='ok', max_length=12)),
                ('managed_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='account.managedpermission')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_permissions', to='billing.product')),
            ],
            options={
                'verbose_name': 'Product permission grant',
                'verbose_name_plural': 'Product permission grants',
                'db_table': 'billing_product_permission_grant',
            },
            managers=[
                ('handleref', django.db.models.manager.Manager()),
            ],
        ),
    ]
