# Generated by Django 3.2.16 on 2023-01-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_auto_20230130_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationproduct',
            name='notes',
            field=models.TextField(blank=True, help_text='Custom notes for why produt access was granted. Useful when access is granted manually', null=True),
        ),
    ]
