# Generated by Django 3.2.16 on 2023-01-31 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0012_alter_service_trial_product"),
        ("billing", "0016_organizationproduct_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="component",
            field=models.ForeignKey(
                blank=True,
                help_text="Product belongs to component",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="applications.service",
            ),
        ),
    ]
