# Generated by Django 3.2.16 on 2023-02-07 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0019_auto_20230203_1129"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="expiry_replacement_product",
            field=models.ForeignKey(
                blank=True,
                help_text="On products that can expire, replace the expired product with this product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expiry_replacement_for",
                to="billing.product",
            ),
        ),
    ]
