# Generated by Django 3.2.20 on 2023-08-08 15:58

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import django_handleref.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_alter_contactmessage_type'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('billing', '0020_product_expiry_replacement_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Invoice Line', 'verbose_name_plural': 'Invoice Lines'},
        ),
        migrations.AlterModelOptions(
            name='ledger',
            options={'verbose_name': 'Ledger', 'verbose_name_plural': 'Ledger'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order Line', 'verbose_name_plural': 'Order Lines'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelManagers(
            name='ledger',
            managers=[
                ('handleref', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='user',
        ),
        migrations.AddField(
            model_name='deposit',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_transaction_set', to='account.organization'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_transaction_set', to='account.organization'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription_cycle_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_set', to='billing.subscriptioncycleproduct'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='created',
            field=django_handleref.models.CreatedDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledger',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='order_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='account.organization'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='status',
            field=models.CharField(choices=[('ok', 'Ok'), ('pending', 'Pending'), ('deactivated', 'Deactivated'), ('failed', 'Failed'), ('expired', 'Expired')], default='ok', max_length=12),
        ),
        migrations.AddField(
            model_name='ledger',
            name='updated',
            field=django_handleref.models.UpdatedDateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_transaction_set', to='account.organization'),
        ),
        migrations.AddField(
            model_name='order',
            name='subscription_cycle_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_set', to='billing.subscriptioncycleproduct'),
        ),
        migrations.AddField(
            model_name='organizationproduct',
            name='component_object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the component object (e.g., Internet exchange id in ixctl)', null=True),
        ),
        migrations.AddField(
            model_name='organizationproduct',
            name='component_object_name',
            field=models.CharField(blank=True, editable=False, help_text='Name of the component object (e.g., Internet exchange name in ixctl) - set automatically during save', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationproduct',
            name='subscription_product',
            field=models.OneToOneField(blank=True, help_text='Product access is granted through this subscription product', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_product', to='billing.subscriptionproduct'),
        ),
        migrations.AddField(
            model_name='payment',
            name='charge_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transaction', to='billing.paymentcharge'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transaction_set', to='account.organization'),
        ),
        migrations.AddField(
            model_name='product',
            name='component_billable_entity',
            field=models.CharField(blank=True, help_text='Links the product to specific entity type in the component (.e.g, InternetExchange for ixctl). Free-form field at this point. Ask developers if you are unsure.', max_length=255, null=True, verbose_name='Billed object'),
        ),
        migrations.AddField(
            model_name='product',
            name='trial_product',
            field=models.ForeignKey(blank=True, help_text="This product's trial version", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_of', to='billing.product'),
        ),
        migrations.AddField(
            model_name='subscriptionproduct',
            name='component_object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the component object (e.g., Internet exchange id in ixctl)', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionproduct',
            name='component_object_name',
            field=models.CharField(blank=True, editable=False, help_text='Name of the component object (e.g., Internet exchange name in ixctl) - set automatically during save', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionproduct',
            name='ends_next_cycle',
            field=models.BooleanField(default=False, help_text='If true, this subscription product will end and be removed at the end of the current subscription cycle'),
        ),
        migrations.AddField(
            model_name='subscriptionproduct',
            name='expires',
            field=models.DateTimeField(blank=True, help_text='If set, this subscription product will end and be removed at the given time', null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_transaction_set', to='account.organization'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='billing_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_money_transaction_set', to='billing.billingcontact'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_set', to='billing.product'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_set', to='billing.subscription'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_set', to='billing.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_set', to='billing.subscription'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_money_transaction_set', to='billing.billingcontact'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='billing_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_money_transaction_set', to='billing.billingcontact'),
        ),
        migrations.CreateModel(
            name='OrganizationProductHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', django_handleref.models.CreatedDateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', django_handleref.models.UpdatedDateTimeField(auto_now=True, verbose_name='Updated')),
                ('version', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('pending', 'Pending'), ('deactivated', 'Deactivated'), ('failed', 'Failed'), ('expired', 'Expired')], default='ok', max_length=12)),
                ('notes', models.TextField(blank=True, help_text='Custom notes for why produt access was granted. Useful when access is granted manually', null=True)),
                ('component_object_id', models.PositiveIntegerField(blank=True, help_text='ID of the component object (e.g., Internet exchange id in ixctl)', null=True)),
                ('component_object_name', models.CharField(blank=True, editable=False, help_text='Name of the component object (e.g., Internet exchange name in ixctl) - set automatically during save', max_length=255, null=True)),
                ('org', models.ForeignKey(help_text='Products the organization has access to', on_delete=django.db.models.deletion.CASCADE, related_name='product_history', to='account.organization')),
                ('product', models.ForeignKey(help_text='Organizations that have access to this product', on_delete=django.db.models.deletion.PROTECT, related_name='organization_history', to='billing.product')),
            ],
            options={
                'verbose_name': 'Organization Product Access History',
                'verbose_name_plural': 'Organization Product Access History',
                'db_table': 'billing_org_product_history',
            },
            managers=[
                ('handleref', django.db.models.manager.Manager()),
            ],
        ),
    ]
