# Generated by Django 3.2.20 on 2023-07-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_product_expiry_replacement_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='component_billable_entity',
            field=models.CharField(blank=True, help_text='Links the product to specific entity type in the component (.e.g, InternetExchange for ixctl). Free-form field at this point. Ask developers if you are unsure.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionproduct',
            name='component_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
