# Generated by Django 3.2.20 on 2023-08-16 12:47

import uuid

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import django_handleref.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0038_alter_contactmessage_type"),
        ("billing", "0022_auto_20230810_1629"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "updated",
                    django_handleref.models.UpdatedDateTimeField(
                        auto_now=True, verbose_name="Updated"
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Ok"),
                            ("pending", "Pending"),
                            ("deactivated", "Deactivated"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="ok",
                        max_length=12,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When transaction was created.",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "USD")], default="USD", max_length=255
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "transaction_id",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("description", models.TextField(blank=True)),
                ("order_number", models.CharField(blank=True, max_length=255)),
                ("invoice_number", models.CharField(blank=True, max_length=255)),
                (
                    "org",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoiceline_transaction_set",
                        to="account.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_set",
                        to="billing.product",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_set",
                        to="billing.subscription",
                    ),
                ),
                (
                    "subscription_cycle_product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_set",
                        to="billing.subscriptioncycleproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Line",
                "verbose_name_plural": "Invoice Lines",
                "db_table": "billing_invoice_line",
            },
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "updated",
                    django_handleref.models.UpdatedDateTimeField(
                        auto_now=True, verbose_name="Updated"
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Ok"),
                            ("pending", "Pending"),
                            ("deactivated", "Deactivated"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="ok",
                        max_length=12,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When transaction was created.",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "USD")], default="USD", max_length=255
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "transaction_id",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("description", models.TextField(blank=True)),
                ("order_number", models.CharField(blank=True, max_length=255)),
                (
                    "org",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orderline_transaction_set",
                        to="account.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_set",
                        to="billing.product",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_set",
                        to="billing.subscription",
                    ),
                ),
                (
                    "subscription_cycle_product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_set",
                        to="billing.subscriptioncycleproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Line",
                "verbose_name_plural": "Order Lines",
                "db_table": "billing_order_line",
            },
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name="order",
            name="org",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="order",
            name="subscription_cycle_product",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
