# Generated by Django 3.2.20 on 2023-07-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_auto_20230727_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionproduct',
            name='ends_next_cycle',
            field=models.BooleanField(default=False, help_text='If true, this subscription product will end and be removed at the end of the current subscription cycle'),
        ),
    ]
