# Generated by Django 3.2.20 on 2023-08-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_subscriptionproduct_ends_next_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationproduct',
            name='component_object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the component object (e.g., Internet exchange id in ixctl)', null=True),
        ),
    ]
