# Generated by Django 3.2.20 on 2023-08-16 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0038_alter_contactmessage_type"),
        ("billing", "0024_auto_20230816_1302"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceline",
            name="org",
        ),
        migrations.RemoveField(
            model_name="orderline",
            name="org",
        ),
        migrations.AlterField(
            model_name="deposit",
            name="org",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deposit_transaction_set",
                to="account.organization",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="org",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_transaction_set",
                to="account.organization",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="org",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="withdrawal_transaction_set",
                to="account.organization",
            ),
            preserve_default=False,
        ),
    ]
