# Generated by Django 3.2.20 on 2023-08-01 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_organizationproduct_component_object_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='organizationproduct',
            name='component_object_id',
        ),
        migrations.AddField(
            model_name='organizationproduct',
            name='subscription_product',
            field=models.OneToOneField(blank=True, help_text='Product access is granted through this subscription product', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_product', to='billing.subscriptionproduct'),
        ),
    ]
