# Generated by Django 3.2.20 on 2023-08-16 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0025_auto_20230816_1339"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Any extra data"
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_set",
                to="billing.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="subscription_cycle_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_set",
                to="billing.subscriptioncycleproduct",
            ),
        ),
    ]
