# Generated by Django 3.2.20 on 2023-08-02 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_handleref.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_alter_contactmessage_type'),
        ('billing', '0025_auto_20230801_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProductHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', django_handleref.models.CreatedDateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', django_handleref.models.UpdatedDateTimeField(auto_now=True, verbose_name='Updated')),
                ('version', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('pending', 'Pending'), ('deactivated', 'Deactivated'), ('failed', 'Failed'), ('expired', 'Expired')], default='ok', max_length=12)),
                ('notes', models.TextField(blank=True, help_text='Custom notes for why produt access was granted. Useful when access is granted manually', null=True)),
                ('component_object_id', models.PositiveIntegerField(blank=True, help_text='ID of the component object (e.g., Internet exchange id in ixctl)', null=True)),
                ('component_object_name', models.CharField(blank=True, editable=False, help_text='Name of the component object (e.g., Internet exchange name in ixctl) - set automatically during save', max_length=255, null=True)),
                ('org', models.ForeignKey(help_text='Products the organization has access to', on_delete=django.db.models.deletion.CASCADE, related_name='product_history', to='account.organization')),
                ('product', models.ForeignKey(help_text='Organizations that have access to this product', on_delete=django.db.models.deletion.PROTECT, related_name='organization_history', to='billing.product')),
            ],
            options={
                'verbose_name': 'Organization Product Access History',
                'verbose_name_plural': 'Organization Product Access History',
                'db_table': 'billing_org_product_history',
            },
            managers=[
                ('handleref', django.db.models.manager.Manager()),
            ],
        ),
    ]
