# Generated by Django 3.2.20 on 2023-08-03 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_organizationproducthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trial_product',
            field=models.ForeignKey(blank=True, help_text="This product's trial version", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_of', to='billing.product'),
        ),
    ]
