# Generated by Django 3.2.20 on 2023-08-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0026_auto_20230816_1548"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("ok", "Ok"), ("failed", "Failed")],
                default="pending",
                max_length=32,
            ),
        ),
    ]
