# Generated by Django 3.2.20 on 2023-08-16 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0027_alter_invoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="charge_object",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice",
                to="billing.paymentcharge",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("ok", "Paid"), ("failed", "Failed")],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_set",
                to="billing.product",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_set",
                to="billing.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="subscription_cycle_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_set",
                to="billing.subscriptioncycleproduct",
            ),
        ),
    ]
