# Generated by Django 3.2.20 on 2023-08-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_product_trial_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationproduct',
            name='component_object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the component object (e.g., Internet exchange id in ixctl)', null=True),
        ),
        migrations.AddField(
            model_name='organizationproduct',
            name='component_object_name',
            field=models.CharField(blank=True, editable=False, help_text='Name of the component object (e.g., Internet exchange name in ixctl) - set automatically during save', max_length=255, null=True),
        ),
    ]
