# Generated by Django 3.2.20 on 2023-08-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_auto_20230803_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionproduct',
            name='expires',
            field=models.DateTimeField(blank=True, help_text='If set, this subscription product will end and be removed at the given time', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='component_billable_entity',
            field=models.CharField(blank=True, help_text='Links the product to specific entity type in the component (.e.g, InternetExchange for ixctl). Free-form field at this point. Ask developers if you are unsure.', max_length=255, null=True, verbose_name='Billed object'),
        ),
    ]
