# Generated by Django 3.2.20 on 2023-10-20 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_auto_20230816_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcharge',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_charge_set', to='billing.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='status',
            field=models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('ok', 'Ok'), ('inactive', 'Inactive')], default='unconfirmed', max_length=32),
        ),
    ]
