# Generated by Django 3.2.23 on 2023-11-10 18:07

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0029_auto_20231020_1706"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingcontact",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None
            ),
        ),
    ]
