# Generated by Django 3.2.20 on 2023-08-08 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_alter_contactmessage_type'),
        ('billing', '0029_auto_20230803_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='user',
        ),
        migrations.AddField(
            model_name='deposit',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_transaction_set', to='account.organization'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_transaction_set', to='account.organization'),
        ),
        migrations.AddField(
            model_name='order',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_transaction_set', to='account.organization'),
        ),
        migrations.AddField(
            model_name='payment',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction_set', to='account.organization'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_transaction_set', to='account.organization'),
        ),
    ]
