# Generated by Django 3.2.20 on 2023-08-08 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0030_auto_20230808_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subscription_cycle_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_set', to='billing.subscriptioncycleproduct'),
        ),
        migrations.AddField(
            model_name='order',
            name='subscription_cycle_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_set', to='billing.subscriptioncycleproduct'),
        ),
    ]
