# Generated by Django 3.2.23 on 2023-11-20 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0030_billingcontact_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingcontact",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=255,
                null=True,
                validators=[django.core.validators.EmailValidator(allowlist=[])],
            ),
        ),
    ]
