# Generated by Django 3.2.20 on 2023-08-08 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0031_auto_20230808_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='charge_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transaction', to='billing.paymentcharge'),
        ),
    ]
