# Generated by Django 3.2.20 on 2023-08-08 15:04

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone
import django_handleref.models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0032_payment_charge_object'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ledger',
            managers=[
                ('handleref', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='ledger',
            name='created',
            field=django_handleref.models.CreatedDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledger',
            name='status',
            field=models.CharField(choices=[('ok', 'Ok'), ('pending', 'Pending'), ('deactivated', 'Deactivated'), ('failed', 'Failed'), ('expired', 'Expired')], default='ok', max_length=12),
        ),
        migrations.AddField(
            model_name='ledger',
            name='updated',
            field=django_handleref.models.UpdatedDateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
