# Generated by Django 3.2.20 on 2023-08-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0033_auto_20230808_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={'verbose_name': 'Ledger', 'verbose_name_plural': 'Ledger'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='order_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ledger',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ledger',
            name='order_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
