# Generated by Django 3.2.23 on 2024-01-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0033_alter_billingcontact_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderhistoryitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, help_text="Price charged", max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="paymentcharge",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price attributed to subscription_cycle for this product",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price charge on initial setup / purchase. For recurring_product pricing this could specify a setup fee. For non-recurring_product pricing, this is the product price.",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="recurringproduct",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price for recurring product charges. For fixed pricing this is the total price charged each subscription cycle. For metered unit this would be the usage price per unit.",
                max_digits=8,
            ),
        ),
    ]
