# Generated by Django 4.2.9 on 2024-02-01 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0034_auto_20240102_1148"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptioncycle",
            name="error_information",
            field=models.TextField(
                blank=True, help_text="Error information", null=True
            ),
        ),
    ]
