# Generated by Django 3.2.20 on 2023-08-08 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_alter_contactmessage_type'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('billing', '0034_auto_20230808_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='account.organization'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='billing_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_money_transaction_set', to='billing.billingcontact'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_transaction_set', to='account.organization'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_transaction_set', to='account.organization'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_set', to='billing.product'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_set', to='billing.subscription'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subscription_cycle_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_set', to='billing.subscriptioncycleproduct'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='order',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_transaction_set', to='account.organization'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_set', to='billing.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_set', to='billing.subscription'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subscription_cycle_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_set', to='billing.subscriptioncycleproduct'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_money_transaction_set', to='billing.billingcontact'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transaction_set', to='account.organization'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='billing_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_money_transaction_set', to='billing.billingcontact'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_transaction_set', to='account.organization'),
        ),
    ]
