# Generated by Django 3.2.20 on 2023-08-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0035_auto_20230808_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='order_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
