# Generated by Django 3.2.20 on 2023-08-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0036_auto_20230808_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
