# Generated by Django 2.2.18 on 2021-02-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_auto_20210211_1413"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="api_url",
            new_name="api_host",
        ),
    ]
