# Generated by Django 3.2.13 on 2022-07-08 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0023_managed_org_perms"),
        ("applications", "0006_service_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="org",
            field=models.ForeignKey(
                blank=True,
                help_text="Service application is exclusive to this organization",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="account.organization",
            ),
        ),
    ]
