# Generated by Django 3.2.13 on 2022-07-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_auto_20220708_1348"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="api_host",
            new_name="api_url",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="invite_redirect",
            new_name="service_url",
        ),
    ]
