# Generated by Django 3.2.14 on 2022-07-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0009_fieldnames"),
    ]

    operations = [
        migrations.RenameField(
            model_name="serviceapiendpoint",
            old_name="svcapp",
            new_name="service_application",
        ),
    ]
