# Generated by Django 3.2.16 on 2023-01-31 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_organizationproduct_notes'),
        ('applications', '0011_service_trial_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='trial_product',
            field=models.ForeignKey(blank=True, help_text='When user is missing permissions to the service.{slug}.{org_id} namespace, use this product to allow the user to unlock access via a trial', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_applications', to='billing.product'),
        ),
    ]
