# Generated by Django 3.2.16 on 2023-04-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='always_show_dashboard',
            field=models.BooleanField(default=True, help_text='Always show the dashboard for this service, even if the user has no permissions'),
        ),
    ]
