# Generated by Django 3.2.16 on 2023-04-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0014_service_always_show_dashboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="cross_promote",
            field=models.BooleanField(
                default=False,
                help_text="If true will show the 'Start trial' alert for this service in other services",
            ),
        ),
    ]
