# Generated by Django 4.2.11 on 2024-04-18 17:03

import django.db.models.deletion
import django.db.models.manager
import django_handleref.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0040_invitation_expiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationWhiteLabeling",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created",
                    django_handleref.models.CreatedDateTimeField(
                        auto_now_add=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated",
                    django_handleref.models.UpdatedDateTimeField(
                        auto_now=True, verbose_name="Updated"
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Ok"),
                            ("pending", "Pending"),
                            ("deactivated", "Deactivated"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="ok",
                        max_length=12,
                    ),
                ),
                ("html_footer", models.TextField(blank=True, null=True)),
                ("css", models.TextField(blank=True, null=True)),
                (
                    "dark_logo_url",
                    models.URLField(
                        blank=True,
                        help_text="URL used to display the dark logo on the dashboard.",
                        max_length=2000,
                        null=True,
                        verbose_name="Logo URL",
                    ),
                ),
                (
                    "light_logo_url",
                    models.URLField(
                        blank=True,
                        help_text="URL used to display the light logo on the dashboard.",
                        max_length=2000,
                        null=True,
                        verbose_name="Logo URL",
                    ),
                ),
                (
                    "show_logo",
                    models.BooleanField(
                        default=False, help_text="Show logo in the services drop down"
                    ),
                ),
                ("http_host", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "org",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
    ]
