# Generated by Django 3.2.23 on 2024-04-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelabel_fullctl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationwhitelabeling',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='organizationwhitelabeling',
            name='dark_logo_url',
            field=models.URLField(help_text='URL used to display the dark logo on the dashboard.', max_length=2000, null=True, verbose_name='Logo URL'),
        ),
        migrations.AddField(
            model_name='organizationwhitelabeling',
            name='light_logo_url',
            field=models.URLField(help_text='URL used to display the light logo on the dashboard.', max_length=2000, null=True, verbose_name='Logo URL'),
        ),
    ]
