# Generated by Django 4.2.11 on 2024-04-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whitelabel_fullctl", "0002_organizationbranding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationbranding",
            name="http_host",
            field=models.CharField(
                blank=True,
                help_text="The HTTP host used to display the branding.",
                max_length=255,
                null=True,
                verbose_name="HTTP Host",
            ),
        ),
    ]
