# Generated by Django 3.2.23 on 2024-04-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whitelabel_fullctl", "0004_auto_20240417_1120"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationwhitelabeling",
            name="html_title",
        ),
    ]
