"""
Django settings for account_service project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

from django.utils.translation import gettext_lazy as _

_DEFAULT_ARG = object()


def print_debug(*args, **kwargs):
    if DEBUG:
        print(*args, **kwargs)


def get_locale_name(code):
    """ Gets the readble name for a locale code. """
    language_map = dict(django.conf.global_settings.LANGUAGES)

    # check for exact match
    if code in language_map:
        return language_map[code]

    # try for the language, fall back to just using the code
    language = code.split("-")[0]
    return language_map.get(language, code)


def set_default(name, value):
    """ Sets the default value for the option if it's not already set. """
    if name not in globals():
        globals()[name] = value


def set_from_env(name, default=_DEFAULT_ARG):
    """
    Sets a global variable from a environment variable of the same name.
    This is useful to leave the option unset and use Django's default (which may change).
    """
    if default is _DEFAULT_ARG and name not in os.environ:
        return

    globals()[name] = os.environ.get(name, default)


def set_option(name, value):
    """ Sets an option, first checking for env vars, then checking for value already set, then going to the default value if passed. """
    if name in os.environ:
        globals()[name] = os.environ.get(name)

    if name not in globals():
        globals()[name] = value


def set_bool(name, value):
    """ Sets and option, first checking for env vars, then checking for value already set, then going to the default value if passed. """
    if name in os.environ:
        envval = os.environ.get(name).lower()
        if envval in ["1", "true", "y", "yes"]:
            globals()[name] = True
        elif envval in ["0", "false", "n", "no"]:
            globals()[name] = False
        else:
            raise ValueError(
                "{} is a boolean, cannot match '{}'".format(name, os.environ[name])
            )

    if name not in globals():
        globals()[name] = value


def try_include(filename):
    """ Tries to include another file from the settings directory. """
    print_debug("including {} {}".format(filename, RELEASE_ENV))
    try:
        with open(filename) as f:
            exec(compile(f.read(), filename, "exec"), globals())

        print_debug("loaded additional settings file '{}'".format(filename))

    except FileNotFoundError:
        print_debug(
            "additional settings file '{}' was not found, skipping".format(filename)
        )
        pass


def read_file(name):
    with open(name) as fh:
        return fh.read()


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))

# set RELEASE_ENV, usually one of dev, beta, tutor, prod
set_option("RELEASE_ENV", "dev")

if RELEASE_ENV == "dev":
    set_bool("DEBUG", True)
else:
    set_bool("DEBUG", False)

# look for mainsite/settings/${RELEASE_ENV}.py and load if it exists
env_file = os.path.join(os.path.dirname(__file__), "{}.py".format(RELEASE_ENV))
try_include(env_file)


print_debug("Release env is '{}'".format(RELEASE_ENV))

# set version, default from /srv/service/etc/VERSION
set_option("PACKAGE_VERSION", read_file(os.path.join(BASE_DIR, "etc/VERSION")).strip())

# Contact email, from address, support email
set_from_env("SERVER_EMAIL")

# django secret key
set_from_env("SECRET_KEY")


# database

set_option("DATABASE_ENGINE", "postgresql_psycopg2")
set_option("DATABASE_HOST", "127.0.0.1")
set_option("DATABASE_PORT", "")
set_option("DATABASE_NAME", "account_service")
set_option("DATABASE_USER", "account_service")
set_option("DATABASE_PASSWORD", "")


# Keys

set_from_env("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY")
set_from_env("SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET")
set_from_env("SOCIAL_AUTH_PEERINGDB_KEY")
set_from_env("SOCIAL_AUTH_PEERINGDB_SECRET")

set_option("RECAPTCHA_PUBLIC_KEY", "...")
set_option("RECAPTCHA_SECRET_KEY", "...")

set_from_env("STRIPE_PUBLIC_KEY")
set_from_env("STRIPE_SECRET_KEY")


# Django config

ALLOWED_HOSTS = ["*"]
SITE_ID = 1

TIME_ZONE = "UTC"
USE_TZ = True

LANGUAGE_CODE = "en-us"
USE_I18N = True
USE_L10N = True

ADMINS = ("Support", SERVER_EMAIL)
MANAGERS = ADMINS

set_option("HOST_URL", "https://localhost:8000")

set_option("MEDIA_ROOT", os.path.abspath(os.path.join(BASE_DIR, "media")))
set_option("MEDIA_URL", f"/m/{PACKAGE_VERSION}/")

set_option("STATIC_ROOT", os.path.abspath(os.path.join(BASE_DIR, "static")))
set_option("STATIC_URL", f"/s/{PACKAGE_VERSION}/")

set_option("SESSION_COOKIE_NAME", "tcacctsid")
# set_from_env("SESSION_COOKIE_DOMAIN")
# set_from_env("SESSION_COOKIE_SECURE")

set_option("DEFAULT_FROM_EMAIL", SERVER_EMAIL)

# TODO - normalize to either use the host or not (preferably not)
LOGIN_URL = "/account/auth/login/"
LOGIN_REDIRECT_URL = "/account"

INVITATION_URL = "{}/auth/invite/".format(HOST_URL)
INVITATION_EMAIL_LIMIT = 5


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "account_service.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "account_service.wsgi.application"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache",
        "OPTIONS": {
            # maximum number of entries in the cache
            "MAX_ENTRIES": 5000,
            # once max entries are reach delete 500 of the oldest entries
            "CULL_FREQUENCY": 10,
        },
    }
}

DATABASES = {
    "default": {
        "ENGINE": f"django.db.backends.{DATABASE_ENGINE}",
        "HOST": DATABASE_HOST,
        "PORT": DATABASE_PORT,
        "NAME": DATABASE_NAME,
        "USER": DATABASE_USER,
        "PASSWORD": DATABASE_PASSWORD,
    }
}


####################### start concat config


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


MIDDLEWARE += ["account.middleware.RequestAugmentation"]

INSTALLED_APPS += (
    # base
    "django.contrib.sites",
    "django_grainy",
    "reversion",
    "captcha",
    "django_handleref",
    "rest_framework",
    # rendering
    "crispy_forms",
    # oauth
    "social_django",
    # account_service apps
    "common",
    "account",
    "billing",
    "applications",
)

CRISPY_TEMPLATE_PACK = "bootstrap4"


AUTHENTICATION_BACKENDS = ["django_grainy.backends.GrainyBackend"]

VALIDATE_PASSWORD_LENGTH = 8


INTERNAL_API_KEY_PERMS = {"account_service": "crud", "fullctl": "crud"}

TEMPLATES[0]["OPTIONS"]["context_processors"] += [
    "account.context_processors.permissions",
    "account.context_processors.info",
]


# INTERNAL

BILLING_COMPONENTS = ["fullctl.prefixctl"]

BILLING_HANDLERS = ["billing.product_handlers.fullctl.PrefixCtlPrefixes"]

BILLING_PROCESSORS = ["billing.payment_processors.stripe.Stripe"]


BILLING_AGREEMENT_NAME = "20C Recurring Services"
BILLING_AGREEMENT_DESCRIPTION = BILLING_AGREEMENT_NAME

BILLING_DEFAULT_CURRENCY = "USD"

set_option("BILLING_ENV", "test")
print_debug("Billing env is '{}'".format(BILLING_ENV))

# OAUTH PROVIDER

INSTALLED_APPS += ["oauth2_provider", "corsheaders"]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "oauth2_provider.middleware.OAuth2TokenMiddleware",
] + MIDDLEWARE

AUTHENTICATION_BACKENDS = [
    "oauth2_provider.backends.OAuth2Backend"
] + AUTHENTICATION_BACKENDS

DEFAULT_SCOPES = ["email", "profile", "peeringdb"]

CORS_ORIGIN_ALLOW_ALL = True

OAUTH2_PROVIDER = {
    "SCOPES": {
        "profile": "user profile",
        "email": "email address",
        "api_keys": "20c api keys",
        "provider:peeringdb": "peeringdb entity associations",
    },
    "ALLOWED_REDIRECT_URI_SCHEMES": ["https", "http"],
    "REQUEST_APPROVAL_PROMPT": "auto",
}

# SOCIAL AUTH

SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

# Supported backends

AUTHENTICATION_BACKENDS = [
    "social_core.backends.google.GoogleOAuth2",
    "account.social_backends.peeringdb.PeeringDBOAuth2",
] + AUTHENTICATION_BACKENDS


SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.social_user",
    "social_core.pipeline.user.get_username",
    "social_core.pipeline.user.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "account.social_backends.pipelines.sync_peeringdb",
    "social_core.pipeline.user.user_details",
)

# We are using postgres so make use of postgres json field

SOCIAL_AUTH_POSTGRES_JSONFIELD = True

# Template Context processors

TEMPLATES[0]["OPTIONS"]["context_processors"] += [
    "social_django.context_processors.backends",
    "social_django.context_processors.login_redirect",
]

# BACKEND: PeeringDB

set_option("PDB_ENDPOINT", "https://peeringdb.com")
PDB_OAUTH_ACCESS_TOKEN_URL = "{}/oauth2/token/".format(PDB_ENDPOINT)
PDB_OAUTH_AUTHORIZE_URL = "{}/oauth2/authorize/".format(PDB_ENDPOINT)
PDB_OAUTH_PROFILE_URL = "{}/profile/v1".format(PDB_ENDPOINT)


# django rest framework

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": ["common.rest.JSONRenderer"],
    "DEFAULT_AUTHENTICATION_CLASSES": (
        #        'rest_framework.authentication.BasicAuthentication',
        "account.rest.authentication.APIKeyAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    # Use hyperlinked styles by default.
    # Only used if the `serializer_class` attribute is not set on a view.
    "DEFAULT_MODEL_SERIALIZER_CLASS": "rest_framework.serializers.HyperlinkedModelSerializer",
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    # Handle rest of permissioning via django-namespace-perms
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    # FIXME: need to somehow allow different drf settings by app
    "EXCEPTION_HANDLER": "common.rest.exception_handler",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "invite": "5/minute",
        "resend_email": "5/minute",
        "password_reset": "5/minute",
    },
}

####################### end concat config

# dynamic config starts here

# enable all languages available in the locale directory
set_option("ENABLE_ALL_LANGUAGES", False)

if ENABLE_ALL_LANGUAGES:
    language_dict = dict(LANGUAGES)
    for locale_path in LOCALE_PATHS:
        for name in os.listdir(locale_path):
            path = os.path.join(locale_path, name)
            if not os.path.isdir(os.path.join(path, "LC_MESSAGES")):
                continue
            code = name.replace("_", "-").lower()
            if code not in language_dict:
                name = _(get_locale_name(code))
                language_dict[code] = name

    LANGUAGES = sorted(language_dict.items())


API_DOC_INCLUDES = {}
API_DOC_PATH = os.path.join(BASE_DIR, "docs", "api")
for _, _, files in os.walk(API_DOC_PATH):
    for file in files:
        base, ext = os.path.splitext(file)
        if ext == ".md":
            API_DOC_INCLUDES[base] = os.path.join(API_DOC_PATH, file)


DEBUG_EMAIL = DEBUG

TEMPLATES[0]["OPTIONS"]["debug"] = DEBUG

# TODO need to figure out logging
# if DEBUG:
#    # make all loggers use the console.
#    for logger in LOGGING["loggers"]:
#        LOGGING["loggers"][logger]["handlers"] = ["console"]
#

# TODO EMAIL_SUBJECT_PREFIX = "[{}] ".format(RELEASE_ENV)

print_debug("loaded settings for version {} (DEBUG: {})".format(PACKAGE_VERSION, DEBUG))
